#!/bin/sh
set -e
deno_version="$__DENO_VERSION__"
dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
if [ ! -d "$dir/.deno" ]; then
  if ! o=$(curl -fsSL https://deno.land/install.sh | DENO_INSTALL="$dir/.deno" sh -s "v$deno_version" 2>&1); then
    echo "$o" >&2
    exit 1
  fi
fi
exec "$dir/.deno/bin/deno" "$@"
